name: deploy
on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: copy file
        run: |
          cp ./script/deploy.sh .
      - name: deploy
        run: |
          chmod +x ./deploy.sh
          sudo ./deploy.sh
