name: deploy

on:
  workflow_dispatch:
  push:
jobs:
  test:
    uses: ./.github/workflows/ci.yml

  deploy:
    runs-on: self-hosted
    if: ${{ needs.test.result == 'success' }}
    needs: test
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order 

      - uses: actions/checkout@v3
      - name: gradle bootjar
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar

      - name: kill 80 port if exist
        run: |
          if sudo lsof -i :80; then
            echo "Port 80 is already in use. Killing the process..."
            sudo lsof -i :80 | awk 'NR!=1 {print $2}' | sudo xargs kill -9
          fi

      - name: deploy
        run: |
          echo $DB_USER
          echo $DB_PASSWORD
          echo $DB_URL
          sudo java -jar -DDB_URL=$DB_URL -DDB_USER=$DB_USER -DDB_PASSWORD=$DB_PASSWORD build/libs/jwp-shopping-order.jar --spring.profiles.active=prod &
        env:
          DB_URL: ${{secrets.DB_URL}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
