name: deploy
on:
  workflow_dispatch:
  push:
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: change permission
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work/jwp-shopping-order

      - uses: actions/checkout@v3
      - name: gradle clean bootjar
        run: |
          chmod +x ./gradlew
          ./gradlew bootjar

      - name: kill 80 port if exist
        run: |
          chmod +x ./script/kill.sh
          sudo ./script/kill.sh

      - name: deploy
        run: |
          sudo java -jar build/libs/jwp-shopping-order.jar --spring.profiles.active=prod &
